// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "lczx/internal/logic/aliyun_oss"
	_ "lczx/internal/logic/auth"
	_ "lczx/internal/logic/cache"
	_ "lczx/internal/logic/captcha"
	_ "lczx/internal/logic/casbin"
	_ "lczx/internal/logic/context"
	_ "lczx/internal/logic/middleware"
	_ "lczx/internal/logic/params_valid"
	_ "lczx/internal/logic/permission_manager"
	_ "lczx/internal/logic/session"
	_ "lczx/internal/logic/system_monitor"
	_ "lczx/internal/logic/user"
	_ "lczx/internal/logic/wdk"
)
