// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "lczx/internal/logic/aliyunoss"
	_ "lczx/internal/logic/auth"
	_ "lczx/internal/logic/cache"
	_ "lczx/internal/logic/captcha"
	_ "lczx/internal/logic/casbin"
	_ "lczx/internal/logic/context"
	_ "lczx/internal/logic/middleware"
	_ "lczx/internal/logic/paramsvalid"
	_ "lczx/internal/logic/permissionmanager"
	_ "lczx/internal/logic/session"
	_ "lczx/internal/logic/systemmonitor"
	_ "lczx/internal/logic/user"
	_ "lczx/internal/logic/wdk"
)
