// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// UserOnline is the golang structure of table user_online for DAO operations like Where/Data.
type UserOnline struct {
	g.Meta   `orm:"table:user_online, do:true"`
	Id       interface{} // 访问ID
	Uuid     interface{} // 用户标识
	Token    interface{} // 用户token
	Passport interface{} // 登录账号
	Browser  interface{} // 浏览器类型
	Os       interface{} // 操作系统
	Ip       interface{} // 登录ip
	Time     *gtime.Time // 登录时间
}
