// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// WdkFile is the golang structure of table wdk_file for DAO operations like Where/Data.
type WdkFile struct {
	g.Meta     `orm:"table:wdk_file, do:true"`
	Id         interface{} // 上传文件ID
	ProjectId  interface{} // 所属项目ID
	Name       interface{} // 文件名称
	Type       interface{} // 文件类型 0:合同扫描文件 1:年度服务计划书 2:总结报告 3:项目移交 4:复盘报告 5:文件签收单 6:满意度调查表
	CreateBy   interface{} // 上传者用户ID
	CreateName interface{} // 上传者姓名
	OriginUrl  interface{} // 原始文件url
	PdfUrl     interface{} // pdf文件url
	CreateAt   *gtime.Time // 上传时间
	UpdateAt   *gtime.Time // 更新时间
}
