// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// WdkServicePhoto is the golang structure of table wdk_service_photo for DAO operations like Where/Data.
type WdkServicePhoto struct {
	g.Meta `orm:"table:wdk_service_photo, do:true"`
	Id     interface{} // 服务记录ID
	Name   interface{} // 照片名称
	Url    interface{} // 照片文件url
}
