// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// WdkServiceRecord is the golang structure of table wdk_service_record for DAO operations like Where/Data.
type WdkServiceRecord struct {
	g.Meta       `orm:"table:wdk_service_record, do:true"`
	Id           interface{} // 服务记录ID
	ProjectId    interface{} // 所属项目ID
	ServiceTime  *gtime.Time // 服务时间
	XchName      interface{} // 行程涵文件名
	XchOriginUrl interface{} // 原始行程涵url
	XchPdfUrl    interface{} // pdf行程涵url
	Remark       interface{} // 备注
	CreateAt     *gtime.Time // 创建时间
}
