// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// WdkProjectBusinessformsDao is the data access object for table wdk_project_businessforms.
type WdkProjectBusinessformsDao struct {
	table   string                         // table is the underlying table name of the DAO.
	group   string                         // group is the database configuration group name of current DAO.
	columns WdkProjectBusinessformsColumns // columns contains all the column names of Table for convenient usage.
}

// WdkProjectBusinessformsColumns defines and stores column names for table wdk_project_businessforms.
type WdkProjectBusinessformsColumns struct {
	ProjectId     string // 文档库项目ID
	BusinessForms string // 业态 0:住宅 1:小高层 2:高层 3:超高层 4:公寓 5:合院 6:叠墅 7:排屋 8:多层 9:会所 10:商住 11:综合体 12:产业园 13:酒店 14:酒店式公寓 15:商业 16:普通商业 17:公共配套 18:办公 19:公寓式办公 20:厂房
}

//  wdkProjectBusinessformsColumns holds the columns for table wdk_project_businessforms.
var wdkProjectBusinessformsColumns = WdkProjectBusinessformsColumns{
	ProjectId:     "project_id",
	BusinessForms: "business_forms",
}

// NewWdkProjectBusinessformsDao creates and returns a new DAO object for table data access.
func NewWdkProjectBusinessformsDao() *WdkProjectBusinessformsDao {
	return &WdkProjectBusinessformsDao{
		group:   "default",
		table:   "wdk_project_businessforms",
		columns: wdkProjectBusinessformsColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *WdkProjectBusinessformsDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *WdkProjectBusinessformsDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *WdkProjectBusinessformsDao) Columns() WdkProjectBusinessformsColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *WdkProjectBusinessformsDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *WdkProjectBusinessformsDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *WdkProjectBusinessformsDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
