// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"lczx/internal/service/internal/dao/internal"
)

// internalAuthRuleDao is internal type for wrapping internal DAO implements.
type internalAuthRuleDao = *internal.AuthRuleDao

// authRuleDao is the data access object for table auth_rule.
// You can define custom methods on it to extend its functionality as you wish.
type authRuleDao struct {
	internalAuthRuleDao
}

var (
	// AuthRule is globally public accessible object for table auth_rule operations.
	AuthRule = authRuleDao{
		internal.NewAuthRuleDao(),
	}
)

// Fill with you ideas below.
