// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"context"
	"github.com/gogf/gf/v2/errors/gerror"
	"lczx/internal/consts"
	"lczx/internal/model/entity"
	"lczx/internal/service/internal/dao/internal"
)

// userDao is the data access object for table user.
// You can define custom methods on it to extend its functionality as you wish.
type userDao struct {
	*internal.UserDao
}

var (
	// User is globally public accessible object for table user operations.
	User = userDao{
		internal.NewUserDao(),
	}
)

// Fill with you ideas below.

// FindUserByPassport 通过账号获取用户信息
func (d *userDao) FindUserByPassport(ctx context.Context, passport string) (user *entity.User, err error) {
	err = d.Ctx(ctx).Where(d.Columns().Passport, passport).Scan(&user)
	if err != nil {
		err = gerror.New(consts.CodeGetUserInfoFailed.Message())
	}

	return user, err
}
