// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"lczx/internal/service/internal/dao/internal"
)

// userExtDao is the data access object for table user_ext.
// You can define custom methods on it to extend its functionality as you wish.
type userExtDao struct {
	*internal.UserExtDao
}

var (
	// UserExt is globally public accessible object for table user_ext operations.
	UserExt = userExtDao{
		internal.NewUserExtDao(),
	}
)

// Fill with you ideas below.
