// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"lczx/internal/service/internal/dao/internal"
)

// internalWdkFiletypeCfgDao is internal type for wrapping internal DAO implements.
type internalWdkFiletypeCfgDao = *internal.WdkFiletypeCfgDao

// wdkFiletypeCfgDao is the data access object for table wdk_filetype_cfg.
// You can define custom methods on it to extend its functionality as you wish.
type wdkFiletypeCfgDao struct {
	internalWdkFiletypeCfgDao
}

var (
	// WdkFiletypeCfg is globally public accessible object for table wdk_filetype_cfg operations.
	WdkFiletypeCfg = wdkFiletypeCfgDao{
		internal.NewWdkFiletypeCfgDao(),
	}
)

// Fill with you ideas below.
