// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"lczx/internal/service/internal/dao/internal"
)

// internalWdkAuditCfgDao is internal type for wrapping internal DAO implements.
type internalWdkAuditCfgDao = *internal.WdkAuditCfgDao

// wdkAuditCfgDao is the data access object for table wdk_audit_cfg.
// You can define custom methods on it to extend its functionality as you wish.
type wdkAuditCfgDao struct {
	internalWdkAuditCfgDao
}

var (
	// WdkAuditCfg is globally public accessible object for table wdk_audit_cfg operations.
	WdkAuditCfg = wdkAuditCfgDao{
		internal.NewWdkAuditCfgDao(),
	}
)

// Fill with you ideas below.
