// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"lczx/internal/service/internal/dao/internal"
)

// internalWdkServiceRecordDao is internal type for wrapping internal DAO implements.
type internalWdkServiceRecordDao = *internal.WdkServiceRecordDao

// wdkServiceRecordDao is the data access object for table wdk_service_record.
// You can define custom methods on it to extend its functionality as you wish.
type wdkServiceRecordDao struct {
	internalWdkServiceRecordDao
}

var (
	// WdkServiceRecord is globally public accessible object for table wdk_service_record operations.
	WdkServiceRecord = wdkServiceRecordDao{
		internal.NewWdkServiceRecordDao(),
	}
)

// Fill with you ideas below.
