// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"lczx/internal/service/internal/dao/internal"
)

// internalWdkAuditFiletypeDao is internal type for wrapping internal DAO implements.
type internalWdkAuditFiletypeDao = *internal.WdkAuditFiletypeDao

// wdkAuditFiletypeDao is the data access object for table wdk_audit_filetype.
// You can define custom methods on it to extend its functionality as you wish.
type wdkAuditFiletypeDao struct {
	internalWdkAuditFiletypeDao
}

var (
	// WdkAuditFiletype is globally public accessible object for table wdk_audit_filetype operations.
	WdkAuditFiletype = wdkAuditFiletypeDao{
		internal.NewWdkAuditFiletypeDao(),
	}
)

// Fill with you ideas below.
