// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"lczx/internal/service/internal/dao/internal"
)

// internalWdkReportDao is internal type for wrapping internal DAO implements.
type internalWdkReportDao = *internal.WdkReportDao

// wdkReportDao is the data access object for table wdk_report.
// You can define custom methods on it to extend its functionality as you wish.
type wdkReportDao struct {
	internalWdkReportDao
}

var (
	// WdkReport is globally public accessible object for table wdk_report operations.
	WdkReport = wdkReportDao{
		internal.NewWdkReportDao(),
	}
)

// Fill with you ideas below.
