// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"lczx/internal/service/internal/dao/internal"
)

// internalWdkReportCommentDao is internal type for wrapping internal DAO implements.
type internalWdkReportCommentDao = *internal.WdkReportCommentDao

// wdkReportCommentDao is the data access object for table wdk_report_comment.
// You can define custom methods on it to extend its functionality as you wish.
type wdkReportCommentDao struct {
	internalWdkReportCommentDao
}

var (
	// WdkReportComment is globally public accessible object for table wdk_report_comment operations.
	WdkReportComment = wdkReportCommentDao{
		internal.NewWdkReportCommentDao(),
	}
)

// Fill with you ideas below.
