// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"lczx/internal/service/internal/dao/internal"
)

// internalWdkFiletypeDao is internal type for wrapping internal DAO implements.
type internalWdkFiletypeDao = *internal.WdkFiletypeDao

// wdkFiletypeDao is the data access object for table wdk_filetype.
// You can define custom methods on it to extend its functionality as you wish.
type wdkFiletypeDao struct {
	internalWdkFiletypeDao
}

var (
	// WdkFiletype is globally public accessible object for table wdk_filetype operations.
	WdkFiletype = wdkFiletypeDao{
		internal.NewWdkFiletypeDao(),
	}
)

// Fill with you ideas below.
