// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"lczx/internal/service/internal/dao/internal"
)

// internalWdkAuditRecordDao is internal type for wrapping internal DAO implements.
type internalWdkAuditRecordDao = *internal.WdkAuditRecordDao

// wdkAuditRecordDao is the data access object for table wdk_audit_record.
// You can define custom methods on it to extend its functionality as you wish.
type wdkAuditRecordDao struct {
	internalWdkAuditRecordDao
}

var (
	// WdkAuditRecord is globally public accessible object for table wdk_audit_record operations.
	WdkAuditRecord = wdkAuditRecordDao{
		internal.NewWdkAuditRecordDao(),
	}
)

// Fill with you ideas below.
