// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"lczx/internal/service/internal/dao/internal"
)

// internalWdkReportAuditTypeDao is internal type for wrapping internal DAO implements.
type internalWdkReportAuditTypeDao = *internal.WdkReportAuditTypeDao

// wdkReportAuditTypeDao is the data access object for table wdk_report_audit_type.
// You can define custom methods on it to extend its functionality as you wish.
type wdkReportAuditTypeDao struct {
	internalWdkReportAuditTypeDao
}

var (
	// WdkReportAuditType is globally public accessible object for table wdk_report_audit_type operations.
	WdkReportAuditType = wdkReportAuditTypeDao{
		internal.NewWdkReportAuditTypeDao(),
	}
)

// Fill with you ideas below.
