// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"lczx/internal/service/internal/dao/internal"
)

// internalWdkFileDao is internal type for wrapping internal DAO implements.
type internalWdkFileDao = *internal.WdkFileDao

// wdkFileDao is the data access object for table wdk_file.
// You can define custom methods on it to extend its functionality as you wish.
type wdkFileDao struct {
	internalWdkFileDao
}

var (
	// WdkFile is globally public accessible object for table wdk_file operations.
	WdkFile = wdkFileDao{
		internal.NewWdkFileDao(),
	}
)

// Fill with you ideas below.
