// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
	"io"
	"lczx/internal/model"

	"github.com/gogf/gf/v2/net/ghttp"
)

type IAliyunOSS interface {
	AuthorizationDownload(filePath string) (fileUrl string, err error)
	BlobDownload(ctx context.Context, filePath string) (body io.ReadCloser, err error)
	UploadImg(file *ghttp.UploadFile, dirPath string) (fileInfo *model.UploadFileInfo, err error)
	UploadFile(file *ghttp.UploadFile, dirPath string) (fileInfo *model.UploadFileInfo, err error)
	UploadImgs(files []*ghttp.UploadFile, dirPath string) (fileInfos []*model.UploadFileInfo, err error)
	UploadFiles(files []*ghttp.UploadFile, dirPath string) (fileInfos []*model.UploadFileInfo, err error)
	GetAccessUrl(ctx context.Context, filePath string) (fileUrl string, err error)
}

var localAliyunOSS IAliyunOSS

func AliyunOSS() IAliyunOSS {
	if localAliyunOSS == nil {
		panic("implement not found for interface IAliyunOSS, forgot register?")
	}
	return localAliyunOSS
}

func RegisterAliyunOSS(i IAliyunOSS) {
	localAliyunOSS = i
}
