// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"

	"github.com/casbin/casbin/v2"
)

type ICasbin interface {
	GetEnforcer(ctx context.Context) (enforcer *casbin.SyncedEnforcer, err error)
}

var localCasbin ICasbin

func Casbin() ICasbin {
	if localCasbin == nil {
		panic("implement not found for interface ICasbin, forgot register?")
	}
	return localCasbin
}

func RegisterCasbin(i ICasbin) {
	localCasbin = i
}
