// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
	"lczx/internal/model"

	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/net/ghttp"
)

type IContext interface {
	Init(req *ghttp.Request, customCtx *model.Context)
	Get(ctx context.Context) (localCtx *model.Context, err error)
	GetUser(ctx context.Context) (user *model.ContextUser, err error)
	GetSession(ctx context.Context) (session *ghttp.Session, err error)
	SetUser(ctx context.Context, ctxUser *model.ContextUser) (err error)
	SetData(ctx context.Context, data g.Map) (err error)
}

var localContext IContext

func Context() IContext {
	if localContext == nil {
		panic("implement not found for interface IContext, forgot register?")
	}
	return localContext
}

func RegisterContext(i IContext) {
	localContext = i
}
