// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
	v1 "lczx/api/v1"
	"lczx/internal/model"
	"lczx/internal/model/entity"

	"github.com/gogf/gf/v2/container/gmap"
)

type IDept interface {
	GetDeptList(ctx context.Context, req *v1.DeptListReq) (list []*entity.Dept, err error)
	AddDept(ctx context.Context, req *v1.DeptAddReq) (err error)
	EditDept(ctx context.Context, req *v1.DeptEditReq) (err error)
	DeleteDept(ctx context.Context, ids []uint64) (err error)
	GetStatusEnableDepts(ctx context.Context) (depts []*entity.Dept, err error)
	GetAllDepts(ctx context.Context) (depts []*entity.Dept, err error)
	GetDeptTree(deptList []*entity.Dept, parentId uint64) (tree []*v1.DeptTreeInfo)
	GetClientOptionMap() map[string][]*model.ClientOption
	DeptExistsById(ctx context.Context, id uint64) (bool, error)
	FindSonIdsByParentId(deptList []*entity.Dept, parentId uint64, idsMap *gmap.Map)
	GetDeptIdsByRoleId(ctx context.Context, id uint64) (deptIds []uint64, err error)
	GetDeptAllNameById(deptList []*entity.Dept, id uint64) (deptAllName string)
	GetDeptNameListById(deptList []*entity.Dept, id uint64, deptNameList *[]string)
	GetDeptById(deptList []*entity.Dept, id uint64) (dept *entity.Dept)
	SelectDeptById(ctx context.Context, id uint64) (dept *entity.Dept, err error)
}

var localDept IDept

func Dept() IDept {
	if localDept == nil {
		panic("implement not found for interface IDept, forgot register?")
	}
	return localDept
}

func RegisterDept(i IDept) {
	localDept = i
}
