// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
	v1 "lczx/api/v1"
	"lczx/internal/model"
	"lczx/internal/model/entity"
)

type ILoginLog interface {
	Invoke(ctx context.Context, data *entity.LoginLog)
	SaveLoginLog(ctx context.Context, data *entity.LoginLog)
	GetLoginLogList(ctx context.Context, req *v1.LoginLogListReq) (total int, list []*entity.LoginLog, err error)
	DeleteLoginLogByIds(ctx context.Context, ids []uint64) (err error)
	ClearLoginLog(ctx context.Context) (err error)
	GetClientOptionMap() map[string][]*model.ClientOption
}

var localLoginLog ILoginLog

func LoginLog() ILoginLog {
	if localLoginLog == nil {
		panic("implement not found for interface ILoginLog, forgot register?")
	}
	return localLoginLog
}

func RegisterLoginLog(i ILoginLog) {
	localLoginLog = i
}
