// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
	v1 "lczx/api/v1"
	"lczx/internal/model/entity"

	"github.com/gogf/gf/v2/container/gmap"
)

type IMenu interface {
	GetMenuList(ctx context.Context, req *v1.MenuListReq) (list []*entity.Menu, err error)
	AddMenu(ctx context.Context, req *v1.MenuAddReq) (err error)
	EditMenu(ctx context.Context, req *v1.MenuEditReq) (err error)
	DeleteMenu(ctx context.Context, ids []uint64) (err error)
	GetIsMenus(ctx context.Context) (list []*entity.Menu, err error)
	GetMenuTree(menuList []*entity.Menu, parentId uint64) (tree []*v1.MenuTreeInfo)
	GetAllMenus(ctx context.Context) (menus []*entity.Menu, err error)
	FindSonIdsByParentId(menuList []*entity.Menu, parentId uint64, idsMap *gmap.Map)
	GetStatusEnableMenus(ctx context.Context) (menuList []*entity.Menu, err error)
	GetMenuById(menuList []*entity.Menu, id uint64) (menu *entity.Menu)
}

var localMenu IMenu

func Menu() IMenu {
	if localMenu == nil {
		panic("implement not found for interface IMenu, forgot register?")
	}
	return localMenu
}

func RegisterMenu(i IMenu) {
	localMenu = i
}
