// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"

	"github.com/gogf/gf/v2/net/ghttp"
)

type IMiddleware interface {
	Ctx(req *ghttp.Request)
	CORS(req *ghttp.Request)
	HandlerResponse(req *ghttp.Request)
	Auth(req *ghttp.Request)
	CheckProjectUpload(ctx context.Context, req *ghttp.Request)
}

var localMiddleware IMiddleware

func Middleware() IMiddleware {
	if localMiddleware == nil {
		panic("implement not found for interface IMiddleware, forgot register?")
	}
	return localMiddleware
}

func RegisterMiddleware(i IMiddleware) {
	localMiddleware = i
}
