// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

type IParamsValid interface {
	RegisterRule()
}

var localParamsValid IParamsValid

func ParamsValid() IParamsValid {
	if localParamsValid == nil {
		panic("implement not found for interface IParamsValid, forgot register?")
	}
	return localParamsValid
}

func RegisterParamsValid(i IParamsValid) {
	localParamsValid = i
}
