// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	v1 "lczx/api/v1"
)

type IServerMonitor interface {
	ServerInfo() (serverInfo *v1.ServerMonitorInfo)
}

var localServerMonitor IServerMonitor

func ServerMonitor() IServerMonitor {
	if localServerMonitor == nil {
		panic("implement not found for interface IServerMonitor, forgot register?")
	}
	return localServerMonitor
}

func RegisterServerMonitor(i IServerMonitor) {
	localServerMonitor = i
}
