// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
	v1 "lczx/api/v1"
	_ "lczx/internal/logic/wdk"
	"lczx/internal/model/entity"
)

type IUserOnline interface {
	Invoke(ctx context.Context, data *entity.UserOnline)
	SaveUserOnline(ctx context.Context, data *entity.UserOnline)
	DeleteOnlineByToken(ctx context.Context, token string)
	GetOnlineList(ctx context.Context, req *v1.UserOnlineListReq, hasToken ...bool) (total int, list []*entity.UserOnline, err error)
	GetOnlineTokensByIds(ctx context.Context, ids []uint64) (tokens []string, err error)
}

var localUserOnline IUserOnline

func UserOnline() IUserOnline {
	if localUserOnline == nil {
		panic("implement not found for interface IUserOnline, forgot register?")
	}
	return localUserOnline
}

func RegisterUserOnline(i IUserOnline) {
	localUserOnline = i
}
