// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
	v1 "lczx/api/v1"
	"lczx/internal/model/entity"
)

type IUser interface {
	GetUserByPassportAndPassword(ctx context.Context, passport, password string) (user *entity.User, err error)
	UpdateUserLogin(ctx context.Context, id uint64, ip string)
	GetProfile(ctx context.Context) (profileInfo *v1.UserProfileInfo, err error)
	SetAvatar(ctx context.Context, avatarUrl string) (err error)
	EditProfile(ctx context.Context, req *v1.UserProfileEditReq) (err error)
	EditPwd(ctx context.Context, oldPassword, newPassword string) (err error)
	GetUserByPassport(ctx context.Context, passport string) (user *entity.User, err error)
	GetUserById(ctx context.Context, id uint64) (user *entity.User, err error)
}

var localUser IUser

func User() IUser {
	if localUser == nil {
		panic("implement not found for interface IUser, forgot register?")
	}
	return localUser
}

func RegisterUser(i IUser) {
	localUser = i
}
