// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
	v1 "lczx/api/v1"
	"lczx/internal/model"
)

type IWdkAttachment interface {
	GetWdkAttachmentRecord(ctx context.Context, projectId uint64) (list []*v1.WdkAttachmentInfo, err error)
	AddWdkAttachment(ctx context.Context, req *v1.WdkAttachmentAddReq, Attachments []*model.UploadFileInfo) (err error)
	DeleteWdkAttachment(ctx context.Context, ids []uint64, projectId uint64) (err error)
}

var localWdkAttachment IWdkAttachment

func WdkAttachment() IWdkAttachment {
	if localWdkAttachment == nil {
		panic("implement not found for interface IWdkAttachment, forgot register?")
	}
	return localWdkAttachment
}

func RegisterWdkAttachment(i IWdkAttachment) {
	localWdkAttachment = i
}
