// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
	v1 "lczx/api/v1"
	"lczx/internal/model/entity"
	"lczx/internal/upload"
)

type IWdkFile interface {
	GetWdkFileRecord(ctx context.Context, projectId uint64) (list []*entity.WdkFile, err error)
	AddWdkFile(ctx context.Context, req *v1.WdkFileAddReq, fileInfos []*upload.FileInfo) (err error)
	GetWdkFileCountByProjectId(ctx context.Context, projectId uint64) (count int, err error)
}

var localWdkFile IWdkFile

func WdkFile() IWdkFile {
	if localWdkFile == nil {
		panic("implement not found for interface IWdkFile, forgot register?")
	}
	return localWdkFile
}

func RegisterWdkFile(i IWdkFile) {
	localWdkFile = i
}
