// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
	v1 "lczx/api/v1"
)

type IWdkReportCfg interface {
	GetWdkReportCfgList(ctx context.Context, name string) (list []*v1.WdkReportCfgInfo, err error)
	GetWdkAllReportCfg(ctx context.Context) (list []*v1.WdkReportCfgInfo, err error)
	AddWdkReportCfg(ctx context.Context, req *v1.WdkReportCfgAddReq) (err error)
	GetWdkReportCfgById(ctx context.Context, id uint64) (wdkReportCfg *v1.WdkReportCfgInfo, err error)
	EditWdkReportCfg(ctx context.Context, req *v1.WdkReportCfgEditReq) (err error)
	DeleteWdkReportCfg(ctx context.Context, ids []uint64) (err error)
	IsWdkReportCfgNameAvailable(ctx context.Context, name string) (bool, error)
	GetWdkReportCfgCount(ctx context.Context) (count int, err error)
	GetWdkReportCfgByIds(ctx context.Context, ids []uint64) (reportCfgInfos []*v1.WdkReportCfgInfo, err error)
}

var localWdkReportCfg IWdkReportCfg

func WdkReportCfg() IWdkReportCfg {
	if localWdkReportCfg == nil {
		panic("implement not found for interface IWdkReportCfg, forgot register?")
	}
	return localWdkReportCfg
}

func RegisterWdkReportCfg(i IWdkReportCfg) {
	localWdkReportCfg = i
}
