// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
	v1 "lczx/api/v1"
	"lczx/internal/model"
)

type IWdkService interface {
	GetWdkServiceRecord(ctx context.Context, projectId uint64) (list []*v1.WdkServiceInfo, err error)
	AddWdkService(ctx context.Context, req *v1.WdkServiceAddReq, xchFile *model.UploadFileInfo, photos []*model.UploadFileInfo) (err error)
	DeleteWdkService(ctx context.Context, ids []uint64) (err error)
}

var localWdkService IWdkService

func WdkService() IWdkService {
	if localWdkService == nil {
		panic("implement not found for interface IWdkService, forgot register?")
	}
	return localWdkService
}

func RegisterWdkService(i IWdkService) {
	localWdkService = i
}
