// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"lczx/internal/dao/internal"
)

// internalWdkReportTypeDao is internal type for wrapping internal DAO implements.
type internalWdkReportTypeDao = *internal.WdkReportTypeDao

// wdkReportTypeDao is the data access object for table wdk_report_type.
// You can define custom methods on it to extend its functionality as you wish.
type wdkReportTypeDao struct {
	internalWdkReportTypeDao
}

var (
	// WdkReportType is globally public accessible object for table wdk_report_type operations.
	WdkReportType = wdkReportTypeDao{
		internal.NewWdkReportTypeDao(),
	}
)

// Fill with you ideas below.
