// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"lczx/internal/dao/internal"
)

// internalWdkAttachmentRecordDao is internal type for wrapping internal DAO implements.
type internalWdkAttachmentRecordDao = *internal.WdkAttachmentRecordDao

// wdkAttachmentRecordDao is the data access object for table wdk_attachment_record.
// You can define custom methods on it to extend its functionality as you wish.
type wdkAttachmentRecordDao struct {
	internalWdkAttachmentRecordDao
}

var (
	// WdkAttachmentRecord is globally public accessible object for table wdk_attachment_record operations.
	WdkAttachmentRecord = wdkAttachmentRecordDao{
		internal.NewWdkAttachmentRecordDao(),
	}
)

// Fill with you ideas below.
