// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"lczx/internal/dao/internal"
)

// internalWdkProjectBusinessformsDao is internal type for wrapping internal DAO implements.
type internalWdkProjectBusinessformsDao = *internal.WdkProjectBusinessformsDao

// wdkProjectBusinessformsDao is the data access object for table wdk_project_businessforms.
// You can define custom methods on it to extend its functionality as you wish.
type wdkProjectBusinessformsDao struct {
	internalWdkProjectBusinessformsDao
}

var (
	// WdkProjectBusinessforms is globally public accessible object for table wdk_project_businessforms operations.
	WdkProjectBusinessforms = wdkProjectBusinessformsDao{
		internal.NewWdkProjectBusinessformsDao(),
	}
)

// Fill with you ideas below.
