// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"lczx/internal/dao/internal"
)

// internalWdkAttachmentFileDao is internal type for wrapping internal DAO implements.
type internalWdkAttachmentFileDao = *internal.WdkAttachmentFileDao

// wdkAttachmentFileDao is the data access object for table wdk_attachment_file.
// You can define custom methods on it to extend its functionality as you wish.
type wdkAttachmentFileDao struct {
	internalWdkAttachmentFileDao
}

var (
	// WdkAttachmentFile is globally public accessible object for table wdk_attachment_file operations.
	WdkAttachmentFile = wdkAttachmentFileDao{
		internal.NewWdkAttachmentFileDao(),
	}
)

// Fill with you ideas below.
