// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"lczx/internal/dao/internal"
)

// internalWdkReportCfgDao is internal type for wrapping internal DAO implements.
type internalWdkReportCfgDao = *internal.WdkReportCfgDao

// wdkReportCfgDao is the data access object for table wdk_report_cfg.
// You can define custom methods on it to extend its functionality as you wish.
type wdkReportCfgDao struct {
	internalWdkReportCfgDao
}

var (
	// WdkReportCfg is globally public accessible object for table wdk_report_cfg operations.
	WdkReportCfg = wdkReportCfgDao{
		internal.NewWdkReportCfgDao(),
	}
)

// Fill with you ideas below.
