// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// AuthRule is the golang structure of table auth_rule for DAO operations like Where/Data.
type AuthRule struct {
	g.Meta     `orm:"table:auth_rule, do:true"`
	Id         interface{} // 规则ID
	ParentId   interface{} // 父规则ID
	ApiPath    interface{} // 接口路径
	ApiName    interface{} // 接口名称
	Condition  interface{} // 条件
	MenuType   interface{} // 类型 0:目录 1:菜单 2:按钮
	Status     interface{} // 菜单状态 0:停用 1:正常
	Show       interface{} // 显示状态 0:隐藏 1:显示
	Path       interface{} // 路由地址
	JumpPath   interface{} // 跳转路由
	Component  interface{} // 组件路径
	IsFrame    interface{} // 是否外链 1是 0否
	ModuleType interface{} // 所属模块
	ModelId    interface{} // 模型ID
	Remark     interface{} // 备注
	CreateAt   *gtime.Time // 创建时间
	UpdateAt   *gtime.Time // 更新时间
	DeletedAt  *gtime.Time // 软删除时间
}
