// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Branch is the golang structure of table branch for DAO operations like Where/Data.
type Branch struct {
	g.Meta `orm:"table:branch, do:true"`
	Id     interface{} // 部门ID
	Name   interface{} // 部门名称
}
