// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// WdkAuditFiletype is the golang structure of table wdk_audit_filetype for DAO operations like Where/Data.
type WdkAuditFiletype struct {
	g.Meta   `orm:"table:wdk_audit_filetype, do:true"`
	AuditUid interface{} // 审核员用户ID
	FileId   interface{} // 审核的文件ID
	TypeId   interface{} // 审核文件类型ID 详见wdk_filetype_cfg配置
}
