// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// WdkAuditCfg is the golang structure of table wdk_audit_cfg for DAO operations like Where/Data.
type WdkAuditCfg struct {
	g.Meta    `orm:"table:wdk_audit_cfg, do:true"`
	TypeId    interface{} // 上传文件类型ID
	AuditUid  interface{} // 审核员用户ID
	AuditName interface{} // 审核员姓名
}
