// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// WdkReportType is the golang structure of table wdk_report_type for DAO operations like Where/Data.
type WdkReportType struct {
	g.Meta   `orm:"table:wdk_report_type, do:true"`
	Id       interface{} // 报告ID
	TypeId   interface{} // 报告类型ID
	TypeName interface{} // 报告类型名称
}
