// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// WdkReportAudit is the golang structure of table wdk_report_audit for DAO operations like Where/Data.
type WdkReportAudit struct {
	g.Meta       `orm:"table:wdk_report_audit, do:true"`
	Id           interface{} // 报告ID
	AuditUid     interface{} // 审核员用户ID
	AuditorType  interface{} // 审核员类型 0:负责人 1:专家组
	ProjectId    interface{} // 所属项目ID
	AuditName    interface{} // 审核员姓名
	Rescind      interface{} // 是否已撤销 0:否 1:是
	Status       interface{} // 审核状态 0:未通过 1:审核中 2:已通过
	Excellence   interface{} // 是否被推荐为优秀报告 0:未被推荐为优秀报告 1:已被推荐为优秀报告
	AuditTime    *gtime.Time // 审核时间
	AuditOpinion interface{} // 审核意见
	CreateAt     *gtime.Time // 创建时间
	UpdateAt     *gtime.Time // 更新时间
}
