// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// WdkReportAuditType is the golang structure of table wdk_report_audit_type for DAO operations like Where/Data.
type WdkReportAuditType struct {
	g.Meta   `orm:"table:wdk_report_audit_type, do:true"`
	AuditUid interface{} // 审核员用户ID
	ReportId interface{} // 审核的报告ID
	TypeId   interface{} // 审核的报告类型ID
	TypeName interface{} // 审核的报告类型名称
}
