// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// WdkAttachmentRecord is the golang structure of table wdk_attachment_record for DAO operations like Where/Data.
type WdkAttachmentRecord struct {
	g.Meta    `orm:"table:wdk_attachment_record, do:true"`
	Id        interface{} // 附件上传记录ID
	ProjectId interface{} // 所属项目ID
	Remark    interface{} // 备注
	CreateAt  *gtime.Time // 创建时间
	UpdateAt  *gtime.Time // 更新时间
	DeletedAt *gtime.Time // 软删除时间
}
