// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// WdkProject is the golang structure of table wdk_project for DAO operations like Where/Data.
type WdkProject struct {
	g.Meta           `orm:"table:wdk_project, do:true"`
	Id               interface{} // 文档库项目ID
	Name             interface{} // 项目名称
	Type             interface{} // 项目性质 0:蓝绿体系 1:非绿
	Origin           interface{} // 项目来源 0:物业公司 1:分子公司 2:老客户 3:自拓
	Step             interface{} // 项目阶段 0:未开始 1:合同签约 2:项目启动会 3:服务中 4:合同结束 5:复盘
	FileUploadStatus interface{} // 项目文件上传状态 0:未传完 1:已传完
	BusinessType     interface{} // 业务类型 0:物业 1:专项 2:全过程
	BusinessForms    interface{} // 业态 0:住宅-综合性住宅 1:住宅-高层住宅 2:住宅-多层住宅 3:住宅-联排别墅 4:住宅-独立式住宅 5:非住宅-办公用房 6:非住宅-场馆（体育馆、博物馆、机场） 7:非住宅-综合类 8:非住宅-学校 9:非住宅-工业园 10:非住宅-医院 11:非住宅-商场 12:非住宅-商铺 13:非住宅-车位 14:非住宅-酒店式公寓 15:非住宅-仓储 16:非住宅-经营用房 17:非住宅-物业用房 18:非住宅-配套用房 19:非住宅-车库 20:非住宅-会所 21:非住宅-临停车位 22:非住宅-非机动车位 23:非住宅-社会福利院 24:非住宅-旅游景区
	ContractStatus   interface{} // 签约状态 0:新签 1:续签
	ContractSum      interface{} // 合同金额
	DeepCulture      interface{} // 是否为深耕 0:否 1:是
	Status           interface{} // 服务状态 0:服务中 1:暂停 2:提前终止 3:正常结束
	EntrustCompany   interface{} // 委托方公司
	SignCompany      interface{} // 我方签订公司 0:绿城房地产咨询集团有限公司 1:浙江幸福绿城房地产咨询有限公司 2:浙江美好绿城房地产咨询有限公司
	PrincipalUid     interface{} // 负责人用户ID
	PrincipalName    interface{} // 负责人姓名
	DeptId           interface{} // 项目所属部门ID
	DeptName         interface{} // 项目所属部门名称
	Region           interface{} // 地区(省/市/区县)
	StartTime        *gtime.Time // 项目开始时间
	EndTime          *gtime.Time // 项目结束时间
	CreateBy         interface{} // 项目创建者用户ID
	CreateName       interface{} // 项目创建者姓名
	UpdatedBy        interface{} // 项目修改者用户ID
	UpdatedName      interface{} // 项目修改者姓名
	Remark           interface{} // 备注
	CreateAt         *gtime.Time // 项目创建时间
	UpdateAt         *gtime.Time // 项目更新时间
	DeletedAt        *gtime.Time // 项目软删除时间
}
