// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// WdkReportAuditRecord is the golang structure of table wdk_report_audit_record for DAO operations like Where/Data.
type WdkReportAuditRecord struct {
	g.Meta    `orm:"table:wdk_report_audit_record, do:true"`
	AuditUid  interface{} // 审核员用户ID
	ReportId  interface{} // 审核的报告ID
	Status    interface{} // 审核状态 0:未通过 1:审核中 2:已通过 3:后台管理员自动通过
	AuditName interface{} // 审核员姓名
	AuditTime *gtime.Time // 审核时间
	CreateAt  *gtime.Time // 创建时间
	UpdateAt  *gtime.Time // 更新时间
}
