// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// WdkProject is the golang structure of table wdk_project for DAO operations like Where/Data.
type WdkProject struct {
	g.Meta           `orm:"table:wdk_project, do:true"`
	Id               interface{} // 文档库项目ID
	Name             interface{} // 项目名称
	Type             interface{} // 项目性质 0:蓝绿体系 1:非绿
	Origin           interface{} // 项目来源 0:物业公司 1:分子公司 2:老客户 3:自拓
	Step             interface{} // 项目阶段 1:合同签约 2:项目启动会 3:服务中 4:合同结束 5:复盘
	FileUploadStatus interface{} // 项目文件上传状态 0:未传完 1:已传完
	BusinessType     interface{} // 业务类型 0:物业 1:专项 3:全过程
	DeepCulture      interface{} // 是否为深耕 0:否 1:是
	Status           interface{} // 服务状态 0:服务中 1:暂停 2:提前终止 3:正常结束
	EntrustCompany   interface{} // 委托方公司
	SignCompany      interface{} // 我方签订公司 0:绿城房地产咨询集团有限公司 1:浙江幸福绿城房地产咨询有限公司 2:浙江美好绿城房地产咨询有限公司
	PrincipalUid     interface{} // 负责人用户ID
	PrincipalName    interface{} // 负责人姓名
	DeptId           interface{} // 项目所属部门ID
	Region           interface{} // 地区(省/市/县)
	StartTime        *gtime.Time // 项目开始时间
	EndTime          *gtime.Time // 项目结束时间
	Remark           interface{} // 备注
	CreateAt         *gtime.Time // 项目创建时间
	UpdateAt         *gtime.Time // 项目更新时间
	DeletedAt        *gtime.Time // 项目软删除时间
}
