// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Branch is the golang structure for table branch.
type Branch struct {
	Id   uint   `json:"id"   ` // 部门ID
	Name string `json:"name" ` // 部门名称
}
