// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Dept is the golang structure for table dept.
type Dept struct {
	Id            uint64      `json:"id"            ` // 部门ID
	ParentId      uint64      `json:"parentId"      ` // 父部门ID
	Name          string      `json:"name"          ` // 部门名称
	Status        uint        `json:"status"        ` // 部门状态 0:停用 1:正常
	CreatedBy     uint64      `json:"createdBy"     ` // 创建人
	UpdatedBy     uint64      `json:"updatedBy"     ` // 修改人
	PrincipalUid  uint64      `json:"principalUid"  ` // 负责人用户ID
	PrincipalName string      `json:"principalName" ` // 负责人姓名
	CreateAt      *gtime.Time `json:"createAt"      ` // 创建时间
	UpdateAt      *gtime.Time `json:"updateAt"      ` // 更新时间
	DeletedAt     *gtime.Time `json:"deletedAt"     ` // 软删除时间
}
