// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Dept is the golang structure for table dept.
type Dept struct {
	Id   uint   `json:"id"   description:"部门ID"` // 部门ID
	Name string `json:"name" description:"部门名称"` // 部门名称
}
