// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// LoginLog is the golang structure for table login_log.
type LoginLog struct {
	Id       uint64      `json:"id"       ` // 访问ID
	Passport string      `json:"passport" ` // 登录账号
	Ip       string      `json:"ip"       ` // 登录IP地址
	Location string      `json:"location" ` // 登录地点
	Browser  string      `json:"browser"  ` // 浏览器类型
	Os       string      `json:"os"       ` // 操作系统
	Status   uint        `json:"status"   ` // 登录状态 0:失败 1:成功
	Msg      string      `json:"msg"      ` // 提示消息
	Time     *gtime.Time `json:"time"     ` // 登录时间
	Module   string      `json:"module"   ` // 登录模块
}
