// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Role is the golang structure for table role.
type Role struct {
	Id        uint64      `json:"id"        ` // 角色ID
	Name      string      `json:"name"      ` // 角色名称
	Status    uint        `json:"status"    ` // 角色状态 0:停用 1:正常
	DataScope uint        `json:"dataScope" ` // 数据范围 1:全部数据权限 2:自定义数据权限 3:本部门数据权限 4:本部门及以下数据权限 5:仅本人数据权限
	Remark    string      `json:"remark"    ` // 备注
	CreateAt  *gtime.Time `json:"createAt"  ` // 创建时间
	UpdateAt  *gtime.Time `json:"updateAt"  ` // 更新时间
}
