// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Role is the golang structure for table role.
type Role struct {
	Id        uint   `json:"id"        description:"角色ID"`                                           // 角色ID
	Status    int    `json:"status"    description:"状态 0:停用 1:正常"`                                   // 状态 0:停用 1:正常
	Name      string `json:"name"      description:"角色名称"`                                           // 角色名称
	Remark    string `json:"remark"    description:"备注"`                                             // 备注
	DataScope int    `json:"dataScope" description:"数据范围 1:全部数据权限 2:自定义数据权限 3:本部门数据权限 4:本部门及以下数据权限"` // 数据范围 1:全部数据权限 2:自定义数据权限 3:本部门数据权限 4:本部门及以下数据权限
}
