// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// UserOnline is the golang structure for table user_online.
type UserOnline struct {
	Id           uint        `json:"id"           ` // 用户ID
	LastLoginAt  *gtime.Time `json:"lastLoginAt"  ` // 最近登录时间
	LastLogoutAt *gtime.Time `json:"lastLogoutAt" ` // 最近登出时间
}
