// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// UserOnline is the golang structure for table user_online.
type UserOnline struct {
	Id       uint64      `json:"id"       ` // 访问ID
	Uuid     string      `json:"uuid"     ` // 用户标识
	Token    string      `json:"token"    ` // 用户token
	Passport string      `json:"passport" ` // 登录账号
	Browser  string      `json:"browser"  ` // 浏览器类型
	Os       string      `json:"os"       ` // 操作系统
	Ip       string      `json:"ip"       ` // 登录ip
	Time     *gtime.Time `json:"time"     ` // 登录时间
}
