// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// UserOnline is the golang structure for table user_online.
type UserOnline struct {
	Id         uint        `json:"id"         ` // 用户ID
	LastTime   *gtime.Time `json:"lastTime"   ` // 最后一次登录时间
	LastIp     string      `json:"lastIp"     ` // 最后一次登录ip
	VisitCount uint        `json:"visitCount" ` // 访问次数
}
