// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// UserExt is the golang structure for table user_ext.
type UserExt struct {
	Id         uint        `json:"id"         description:"用户ID"`     // 用户ID
	LastTime   *gtime.Time `json:"lastTime"   description:"最后一次登录时间"` // 最后一次登录时间
	LastIp     string      `json:"lastIp"     description:"最后一次登录ip"` // 最后一次登录ip
	VisitCount uint        `json:"visitCount" description:"访问次数"`     // 访问次数
}
