// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// WdkServicePhoto is the golang structure for table wdk_service_photo.
type WdkServicePhoto struct {
	Id   uint64 `json:"id"   ` // 服务记录ID
	Name string `json:"name" ` // 照片名称
	Url  string `json:"url"  ` // 照片文件url
}
