// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// WdkFile is the golang structure for table wdk_file.
type WdkFile struct {
	FileId       uint64      `json:"fileId"       description:"上传文件ID"`                                            // 上传文件ID
	ProjectId    uint64      `json:"projectId"    description:"所属项目ID"`                                            // 所属项目ID
	Name         string      `json:"name"         description:"文件名"`                                               // 文件名
	CreateBy     uint64      `json:"createBy"     description:"上传者用户ID"`                                           // 上传者用户ID
	CreateName   string      `json:"createName"   description:"上传者姓名"`                                             // 上传者姓名
	AuditStatus  uint        `json:"auditStatus"  description:"审核状态 0:不需要审核 1:审核中 2:已通过 3:未通过"`                    // 审核状态 0:不需要审核 1:审核中 2:已通过 3:未通过
	AuditNames   string      `json:"auditNames"   description:"审核人员们的姓名"`                                          // 审核人员们的姓名
	AuditEndTime *gtime.Time `json:"auditEndTime" description:"审核完成时间"`                                            // 审核完成时间
	Step         uint        `json:"step"         description:"所属项目阶段 0:未开始 1:合同签约 2:项目启动会 3:服务中 4:合同结束 5:复盘"`     // 所属项目阶段 0:未开始 1:合同签约 2:项目启动会 3:服务中 4:合同结束 5:复盘
	Excellence   uint        `json:"excellence"   description:"是否是优秀报告 0:无该属性 1:被推荐为优秀报告 2:未被评选为优秀报告 3:已被评选为优秀报告"` // 是否是优秀报告 0:无该属性 1:被推荐为优秀报告 2:未被评选为优秀报告 3:已被评选为优秀报告
	OriginUrl    string      `json:"originUrl"    description:"原始文件url"`                                           // 原始文件url
	PdfUrl       string      `json:"pdfUrl"       description:"pdf文件url"`                                          // pdf文件url
	CreateAt     *gtime.Time `json:"createAt"     description:"上传时间"`                                              // 上传时间
	UpdateAt     *gtime.Time `json:"updateAt"     description:"更新时间"`                                              // 更新时间
	DeletedAt    *gtime.Time `json:"deletedAt"    description:"软删除时间"`                                             // 软删除时间
}
