// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// WdkFileComment is the golang structure for table wdk_file_comment.
type WdkFileComment struct {
	AuditUid  uint64      `json:"auditUid"  description:"审核员用户ID"` // 审核员用户ID
	FileId    uint64      `json:"fileId"    description:"审核的文件ID"` // 审核的文件ID
	Page      uint        `json:"page"      description:"文件页码"`    // 文件页码
	AuditName string      `json:"auditName" description:"审核人员姓名"`  // 审核人员姓名
	Comment   string      `json:"comment"   description:"每页评价内容"`  // 每页评价内容
	CreateAt  *gtime.Time `json:"createAt"  description:"创建时间"`    // 创建时间
	UpdateAt  *gtime.Time `json:"updateAt"  description:"更新时间"`    // 更新时间
	DeletedAt *gtime.Time `json:"deletedAt" description:"软删除时间"`   // 软删除时间
}
