// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// WdkReportAuditType is the golang structure for table wdk_report_audit_type.
type WdkReportAuditType struct {
	Id          uint64 `json:"id"          ` // 报告ID
	AuditUid    uint64 `json:"auditUid"    ` // 审核员用户ID
	AuditorType uint   `json:"auditorType" ` // 审核员类型 0:负责人 1:专家组
	TypeId      uint64 `json:"typeId"      ` // 报告类型ID
	TypeName    string `json:"typeName"    ` // 报告类型名称
}
