// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// WdkAttachmentRecord is the golang structure for table wdk_attachment_record.
type WdkAttachmentRecord struct {
	Id        uint64      `json:"id"        description:"附件上传记录ID"` // 附件上传记录ID
	ProjectId uint64      `json:"projectId" description:"所属项目ID"`   // 所属项目ID
	Remark    string      `json:"remark"    description:"备注"`       // 备注
	CreateAt  *gtime.Time `json:"createAt"  description:"创建时间"`     // 创建时间
}
