// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// WdkAttachmentRecord is the golang structure for table wdk_attachment_record.
type WdkAttachmentRecord struct {
	Id        uint64      `json:"id"        ` // 附件上传记录ID
	ProjectId uint64      `json:"projectId" ` // 所属项目ID
	Remark    string      `json:"remark"    ` // 备注
	CreateAt  *gtime.Time `json:"createAt"  ` // 创建时间
}
