// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// WdkReportCfg is the golang structure for table wdk_report_cfg.
type WdkReportCfg struct {
	Id       uint64      `json:"id"       ` // 报告类型ID
	Name     string      `json:"name"     ` // 报告类型名称
	CreateAt *gtime.Time `json:"createAt" ` // 创建时间
	UpdateAt *gtime.Time `json:"updateAt" ` // 更新时间
}
