// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// WdkReportAuditType is the golang structure for table wdk_report_audit_type.
type WdkReportAuditType struct {
	Id          uint64 `json:"id"          description:"报告ID"`              // 报告ID
	AuditUid    uint64 `json:"auditUid"    description:"审核员用户ID"`           // 审核员用户ID
	AuditorType uint   `json:"auditorType" description:"审核员类型 0:负责人 1:专家组"` // 审核员类型 0:负责人 1:专家组
	TypeId      uint64 `json:"typeId"      description:"报告类型ID"`            // 报告类型ID
	TypeName    string `json:"typeName"    description:"报告类型名称"`            // 报告类型名称
}
