// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// WdkProject is the golang structure for table wdk_project.
type WdkProject struct {
	Id               uint64      `json:"id"               ` // 文档库项目ID
	Name             string      `json:"name"             ` // 项目名称
	Type             uint        `json:"type"             ` // 项目性质 0:蓝绿体系 1:非绿
	Origin           uint        `json:"origin"           ` // 项目来源 0:物业公司 1:分子公司 2:老客户 3:自拓
	Step             uint        `json:"step"             ` // 项目阶段 0:未开始 1:合同签约 2:项目启动会 3:服务中 4:合同结束 5:复盘
	FileUploadStatus uint        `json:"fileUploadStatus" ` // 项目文件上传状态 0:未传完 1:已传完
	BusinessType     uint        `json:"businessType"     ` // 业务类型 0:物业 1:专项 2:全过程
	ContractStatus   uint        `json:"contractStatus"   ` // 签约状态 0:新签 1:续签
	ContractSum      float64     `json:"contractSum"      ` // 合同金额
	DeepCulture      uint        `json:"deepCulture"      ` // 是否为深耕 0:否 1:是
	Status           uint        `json:"status"           ` // 服务状态 0:服务中 1:暂停 2:提前终止 3:跟踪期 4:洽谈中
	EntrustCompany   string      `json:"entrustCompany"   ` // 委托方公司
	SignCompany      uint        `json:"signCompany"      ` // 我方签订公司 0:绿城房地产咨询集团有限公司 1:浙江幸福绿城房地产咨询有限公司 2:浙江美好绿城房地产咨询有限公司
	PrincipalUid     uint64      `json:"principalUid"     ` // 负责人用户ID
	PrincipalName    string      `json:"principalName"    ` // 负责人姓名
	DeptId           uint64      `json:"deptId"           ` // 项目所属部门ID
	DeptName         string      `json:"deptName"         ` // 项目所属部门名称
	Region           string      `json:"region"           ` // 地区(省/市/区县)
	StartTime        *gtime.Time `json:"startTime"        ` // 项目开始时间
	EndTime          *gtime.Time `json:"endTime"          ` // 项目结束时间
	CreateBy         uint64      `json:"createBy"         ` // 项目创建者用户ID
	CreateName       string      `json:"createName"       ` // 项目创建者姓名
	UpdatedBy        uint64      `json:"updatedBy"        ` // 项目修改者用户ID
	UpdatedName      string      `json:"updatedName"      ` // 项目修改者姓名
	Remark           string      `json:"remark"           ` // 备注
	CreateAt         *gtime.Time `json:"createAt"         ` // 项目创建时间
	UpdateAt         *gtime.Time `json:"updateAt"         ` // 项目更新时间
	DeletedAt        *gtime.Time `json:"deletedAt"        ` // 项目软删除时间
}
