// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// WdkReportComment is the golang structure for table wdk_report_comment.
type WdkReportComment struct {
	AuditUid  uint64      `json:"auditUid"  description:"审核员用户ID"` // 审核员用户ID
	ReportId  uint64      `json:"reportId"  description:"审核报告ID"`  // 审核报告ID
	Page      uint        `json:"page"      description:"文件页码"`    // 文件页码
	AuditName string      `json:"auditName" description:"审核人员姓名"`  // 审核人员姓名
	Comment   string      `json:"comment"   description:"每页评价内容"`  // 每页评价内容
	CreateAt  *gtime.Time `json:"createAt"  description:"创建时间"`    // 创建时间
	UpdateAt  *gtime.Time `json:"updateAt"  description:"更新时间"`    // 更新时间
}
