// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// WdkAttachmentFile is the golang structure for table wdk_attachment_file.
type WdkAttachmentFile struct {
	Id        uint64 `json:"id"        ` // 附件上传记录ID
	Name      string `json:"name"      ` // 附件名
	OriginUrl string `json:"originUrl" ` // 原始附件url
	PdfUrl    string `json:"pdfUrl"    ` // pdf附件url
}
