// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// WdkProjectBusinessforms is the golang structure for table wdk_project_businessforms.
type WdkProjectBusinessforms struct {
	ProjectId     uint64 `json:"projectId"     description:"文档库项目ID"`                                                                                                                     // 文档库项目ID
	BusinessForms uint   `json:"businessForms" description:"业态 0:住宅 1:小高层 2:高层 3:超高层 4:公寓 5:合院 6:叠墅 7:排屋 8:多层 9:会所 10:商住 11:综合体 12:产业园 13:酒店 14:酒店式公寓 15:商业 16:普通商业 17:公共配套 18:办公 19:厂房"` // 业态 0:住宅 1:小高层 2:高层 3:超高层 4:公寓 5:合院 6:叠墅 7:排屋 8:多层 9:会所 10:商住 11:综合体 12:产业园 13:酒店 14:酒店式公寓 15:商业 16:普通商业 17:公共配套 18:办公 19:厂房
}
