// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// WdkAttachmentRecord is the golang structure for table wdk_attachment_record.
type WdkAttachmentRecord struct {
	Id        uint64      `json:"id"        description:"附件上传记录ID"` // 附件上传记录ID
	Remark    string      `json:"remark"    description:"备注"`       // 备注
	CreateAt  *gtime.Time `json:"createAt"  description:"创建时间"`     // 创建时间
	UpdateAt  *gtime.Time `json:"updateAt"  description:"更新时间"`     // 更新时间
	DeletedAt *gtime.Time `json:"deletedAt" description:"软删除时间"`    // 软删除时间
}
