// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// WdkProject is the golang structure for table wdk_project.
type WdkProject struct {
	Id               uint64      `json:"id"               description:"文档库项目ID"`                                                                                                                           // 文档库项目ID
	Name             string      `json:"name"             description:"项目名称"`                                                                                                                              // 项目名称
	Type             uint        `json:"type"             description:"项目性质 0:蓝绿体系 1:非绿"`                                                                                                                  // 项目性质 0:蓝绿体系 1:非绿
	Origin           uint        `json:"origin"           description:"项目来源 0:绿中 1:分子公司 2:合伙人 3:老客户 4:中交 5:蓝城 6:自拓 7:其他"`                                                                                  // 项目来源 0:绿中 1:分子公司 2:合伙人 3:老客户 4:中交 5:蓝城 6:自拓 7:其他
	Step             uint        `json:"step"             description:"项目阶段 0:未开始 1:合同签约 2:项目启动会 3:服务中-规划设计 4:服务中-项目展示区施工 5:服务中-主体结构工程 6:服务中-主体安装工程 7:服务中-装饰装修工程 8:服务中-景观市政工程 9:服务中-项目交付验收 30:合同结束 31:复盘"` // 项目阶段 0:未开始 1:合同签约 2:项目启动会 3:服务中-规划设计 4:服务中-项目展示区施工 5:服务中-主体结构工程 6:服务中-主体安装工程 7:服务中-装饰装修工程 8:服务中-景观市政工程 9:服务中-项目交付验收 30:合同结束 31:复盘
	FileUploadStatus uint        `json:"fileUploadStatus" description:"项目文件上传状态 0:异常 1:正常 2:已完成"`                                                                                                          // 项目文件上传状态 0:异常 1:正常 2:已完成
	BusinessType     uint        `json:"businessType"     description:"业务类型 0:物业 1:专项 2:全过程"`                                                                                                              // 业务类型 0:物业 1:专项 2:全过程
	ContractStatus   uint        `json:"contractStatus"   description:"签约状态 0:新签 1:续签 2:未签"`                                                                                                               // 签约状态 0:新签 1:续签 2:未签
	ContractSum      float64     `json:"contractSum"      description:"合同金额"`                                                                                                                              // 合同金额
	DeepCulture      uint        `json:"deepCulture"      description:"是否为深耕 0:否 1:是"`                                                                                                                     // 是否为深耕 0:否 1:是
	Status           uint        `json:"status"           description:"服务状态 0:服务中 1:暂停 2:提前终止 3:跟踪期 4:洽谈中"`                                                                                                // 服务状态 0:服务中 1:暂停 2:提前终止 3:跟踪期 4:洽谈中
	EntrustCompany   string      `json:"entrustCompany"   description:"委托方公司"`                                                                                                                             // 委托方公司
	SignCompany      uint        `json:"signCompany"      description:"我方签订公司 0:绿城房地产咨询集团有限公司 1:浙江幸福绿城房地产咨询有限公司 2:浙江美好绿城房地产咨询有限公司"`                                                                        // 我方签订公司 0:绿城房地产咨询集团有限公司 1:浙江幸福绿城房地产咨询有限公司 2:浙江美好绿城房地产咨询有限公司
	PrincipalUid     uint64      `json:"principalUid"     description:"负责人用户ID"`                                                                                                                           // 负责人用户ID
	PrincipalName    string      `json:"principalName"    description:"负责人姓名"`                                                                                                                             // 负责人姓名
	DeptId           uint64      `json:"deptId"           description:"项目所属部门ID"`                                                                                                                          // 项目所属部门ID
	DeptName         string      `json:"deptName"         description:"项目所属部门名称"`                                                                                                                          // 项目所属部门名称
	Region           string      `json:"region"           description:"地区(省/市/区县)"`                                                                                                                        // 地区(省/市/区县)
	StartTime        *gtime.Time `json:"startTime"        description:"项目开始时间"`                                                                                                                            // 项目开始时间
	EndTime          *gtime.Time `json:"endTime"          description:"项目结束时间"`                                                                                                                            // 项目结束时间
	CreateBy         uint64      `json:"createBy"         description:"项目创建者用户ID"`                                                                                                                         // 项目创建者用户ID
	CreateName       string      `json:"createName"       description:"项目创建者姓名"`                                                                                                                           // 项目创建者姓名
	UpdatedBy        uint64      `json:"updatedBy"        description:"项目修改者用户ID"`                                                                                                                         // 项目修改者用户ID
	UpdatedName      string      `json:"updatedName"      description:"项目修改者姓名"`                                                                                                                           // 项目修改者姓名
	Remark           string      `json:"remark"           description:"备注"`                                                                                                                                // 备注
	CreateAt         *gtime.Time `json:"createAt"         description:"项目创建时间"`                                                                                                                            // 项目创建时间
	UpdateAt         *gtime.Time `json:"updateAt"         description:"项目更新时间"`                                                                                                                            // 项目更新时间
	DeletedAt        *gtime.Time `json:"deletedAt"        description:"项目软删除时间"`                                                                                                                           // 项目软删除时间
}
