// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// WdkReportAuditCfg is the golang structure for table wdk_report_audit_cfg.
type WdkReportAuditCfg struct {
	Id        uint64 `json:"id"        description:"报告类型ID"`  // 报告类型ID
	AuditUid  uint64 `json:"auditUid"  description:"审核员用户ID"` // 审核员用户ID
	AuditName string `json:"auditName" description:"审核员姓名"`   // 审核员姓名
}
