// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// WdkAuditCfg is the golang structure for table wdk_audit_cfg.
type WdkAuditCfg struct {
	TypeId    uint64 `json:"typeId"    description:"上传文件类型ID"` // 上传文件类型ID
	AuditUid  uint64 `json:"auditUid"  description:"审核员用户ID"`  // 审核员用户ID
	AuditName string `json:"auditName" description:"审核员姓名"`    // 审核员姓名
}
