// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// WdkReportAuditCfg is the golang structure for table wdk_report_audit_cfg.
type WdkReportAuditCfg struct {
	Id        uint64 `json:"id"        ` // 报告类型ID
	AuditUid  uint64 `json:"auditUid"  ` // 审核员用户ID
	TypeName  string `json:"typeName"  ` // 报告类型名称
	AuditName string `json:"auditName" ` // 审核员姓名
}
