// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// WdkServicePhoto is the golang structure for table wdk_service_photo.
type WdkServicePhoto struct {
	Id   uint64 `json:"id"   description:"服务记录ID"`  // 服务记录ID
	Name string `json:"name" description:"照片名称"`    // 照片名称
	Url  string `json:"url"  description:"照片文件url"` // 照片文件url
}
