// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// WdkServiceRecord is the golang structure for table wdk_service_record.
type WdkServiceRecord struct {
	Id           uint64      `json:"id"           ` // 服务记录ID
	ProjectId    uint64      `json:"projectId"    ` // 所属项目ID
	ServiceTime  *gtime.Time `json:"serviceTime"  ` // 服务时间
	XchName      string      `json:"xchName"      ` // 行程涵文件名
	XchOriginUrl string      `json:"xchOriginUrl" ` // 原始行程涵url
	XchPdfUrl    string      `json:"xchPdfUrl"    ` // pdf行程涵url
	Remark       string      `json:"remark"       ` // 备注
	CreateAt     *gtime.Time `json:"createAt"     ` // 创建时间
}
