// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// UserExtDao is the data access object for table user_ext.
type UserExtDao struct {
	table   string         // table is the underlying table name of the DAO.
	group   string         // group is the database configuration group name of current DAO.
	columns UserExtColumns // columns contains all the column names of Table for convenient usage.
}

// UserExtColumns defines and stores column names for table user_ext.
type UserExtColumns struct {
	Id        string // 用户ID
	BranchId  string // 部门ID
	ZskRoleId string // 知识库角色ID 0: 默认普通用户 1000: 超级管理员 900: 普通管理员
	WdkRoleId string // 文档库角色ID 0: 默认普通用户 1000: 超级管理员 900: 普通管理员
}

//  userExtColumns holds the columns for table user_ext.
var userExtColumns = UserExtColumns{
	Id:        "id",
	BranchId:  "branch_id",
	ZskRoleId: "zsk_role_id",
	WdkRoleId: "wdk_role_id",
}

// NewUserExtDao creates and returns a new DAO object for table data access.
func NewUserExtDao() *UserExtDao {
	return &UserExtDao{
		group:   "default",
		table:   "user_ext",
		columns: userExtColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *UserExtDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *UserExtDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *UserExtDao) Columns() UserExtColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *UserExtDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *UserExtDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *UserExtDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
