// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// WdkReportCommentDao is the data access object for table wdk_report_comment.
type WdkReportCommentDao struct {
	table   string                  // table is the underlying table name of the DAO.
	group   string                  // group is the database configuration group name of current DAO.
	columns WdkReportCommentColumns // columns contains all the column names of Table for convenient usage.
}

// WdkReportCommentColumns defines and stores column names for table wdk_report_comment.
type WdkReportCommentColumns struct {
	AuditUid  string // 审核员用户ID
	ReportId  string // 审核报告ID
	Page      string // 文件页码
	AuditName string // 审核人员姓名
	Comment   string // 每页评价内容
	CreateAt  string // 创建时间
	UpdateAt  string // 更新时间
}

//  wdkReportCommentColumns holds the columns for table wdk_report_comment.
var wdkReportCommentColumns = WdkReportCommentColumns{
	AuditUid:  "audit_uid",
	ReportId:  "report_id",
	Page:      "page",
	AuditName: "audit_name",
	Comment:   "comment",
	CreateAt:  "create_at",
	UpdateAt:  "update_at",
}

// NewWdkReportCommentDao creates and returns a new DAO object for table data access.
func NewWdkReportCommentDao() *WdkReportCommentDao {
	return &WdkReportCommentDao{
		group:   "default",
		table:   "wdk_report_comment",
		columns: wdkReportCommentColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *WdkReportCommentDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *WdkReportCommentDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *WdkReportCommentDao) Columns() WdkReportCommentColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *WdkReportCommentDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *WdkReportCommentDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *WdkReportCommentDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
