// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// WdkAuditRecordDao is the data access object for table wdk_audit_record.
type WdkAuditRecordDao struct {
	table   string                // table is the underlying table name of the DAO.
	group   string                // group is the database configuration group name of current DAO.
	columns WdkAuditRecordColumns // columns contains all the column names of Table for convenient usage.
}

// WdkAuditRecordColumns defines and stores column names for table wdk_audit_record.
type WdkAuditRecordColumns struct {
	AuditUid  string // 审核员用户ID
	FileId    string // 需要审核的文件ID
	Status    string // 审核状态 1:审核中 2:已通过 3:未通过
	AuditTime string // 审核时间
	AuditName string // 审核员姓名
	CreateAt  string // 创建时间
	UpdateAt  string // 更新时间
	DeletedAt string // 软删除时间
}

//  wdkAuditRecordColumns holds the columns for table wdk_audit_record.
var wdkAuditRecordColumns = WdkAuditRecordColumns{
	AuditUid:  "audit_uid",
	FileId:    "file_id",
	Status:    "status",
	AuditTime: "audit_time",
	AuditName: "audit_name",
	CreateAt:  "create_at",
	UpdateAt:  "update_at",
	DeletedAt: "deleted_at",
}

// NewWdkAuditRecordDao creates and returns a new DAO object for table data access.
func NewWdkAuditRecordDao() *WdkAuditRecordDao {
	return &WdkAuditRecordDao{
		group:   "default",
		table:   "wdk_audit_record",
		columns: wdkAuditRecordColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *WdkAuditRecordDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *WdkAuditRecordDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *WdkAuditRecordDao) Columns() WdkAuditRecordColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *WdkAuditRecordDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *WdkAuditRecordDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *WdkAuditRecordDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
