// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// WdkReportAuditRecordDao is the data access object for table wdk_report_audit_record.
type WdkReportAuditRecordDao struct {
	table   string                      // table is the underlying table name of the DAO.
	group   string                      // group is the database configuration group name of current DAO.
	columns WdkReportAuditRecordColumns // columns contains all the column names of Table for convenient usage.
}

// WdkReportAuditRecordColumns defines and stores column names for table wdk_report_audit_record.
type WdkReportAuditRecordColumns struct {
	AuditUid  string // 审核员用户ID
	ReportId  string // 审核的报告ID
	Status    string // 审核状态 0:未通过 1:审核中 2:已通过 3:后台管理员自动通过
	AuditName string // 审核员姓名
	AuditTime string // 审核时间
	CreateAt  string // 创建时间
	UpdateAt  string // 更新时间
}

//  wdkReportAuditRecordColumns holds the columns for table wdk_report_audit_record.
var wdkReportAuditRecordColumns = WdkReportAuditRecordColumns{
	AuditUid:  "audit_uid",
	ReportId:  "report_id",
	Status:    "status",
	AuditName: "audit_name",
	AuditTime: "audit_time",
	CreateAt:  "create_at",
	UpdateAt:  "update_at",
}

// NewWdkReportAuditRecordDao creates and returns a new DAO object for table data access.
func NewWdkReportAuditRecordDao() *WdkReportAuditRecordDao {
	return &WdkReportAuditRecordDao{
		group:   "default",
		table:   "wdk_report_audit_record",
		columns: wdkReportAuditRecordColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *WdkReportAuditRecordDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *WdkReportAuditRecordDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *WdkReportAuditRecordDao) Columns() WdkReportAuditRecordColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *WdkReportAuditRecordDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *WdkReportAuditRecordDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *WdkReportAuditRecordDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
