// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// WdkReportAuditTypeDao is the data access object for table wdk_report_audit_type.
type WdkReportAuditTypeDao struct {
	table   string                    // table is the underlying table name of the DAO.
	group   string                    // group is the database configuration group name of current DAO.
	columns WdkReportAuditTypeColumns // columns contains all the column names of Table for convenient usage.
}

// WdkReportAuditTypeColumns defines and stores column names for table wdk_report_audit_type.
type WdkReportAuditTypeColumns struct {
	Id          string // 报告ID
	AuditUid    string // 审核员用户ID
	AuditorType string // 审核员类型 0:负责人 1:专家组
	TypeId      string // 报告类型ID
	TypeName    string // 报告类型名称
}

//  wdkReportAuditTypeColumns holds the columns for table wdk_report_audit_type.
var wdkReportAuditTypeColumns = WdkReportAuditTypeColumns{
	Id:          "id",
	AuditUid:    "audit_uid",
	AuditorType: "auditor_type",
	TypeId:      "type_id",
	TypeName:    "type_name",
}

// NewWdkReportAuditTypeDao creates and returns a new DAO object for table data access.
func NewWdkReportAuditTypeDao() *WdkReportAuditTypeDao {
	return &WdkReportAuditTypeDao{
		group:   "default",
		table:   "wdk_report_audit_type",
		columns: wdkReportAuditTypeColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *WdkReportAuditTypeDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *WdkReportAuditTypeDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *WdkReportAuditTypeDao) Columns() WdkReportAuditTypeColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *WdkReportAuditTypeDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *WdkReportAuditTypeDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *WdkReportAuditTypeDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
