// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// WdkServiceRecordDao is the data access object for table wdk_service_record.
type WdkServiceRecordDao struct {
	table   string                  // table is the underlying table name of the DAO.
	group   string                  // group is the database configuration group name of current DAO.
	columns WdkServiceRecordColumns // columns contains all the column names of Table for convenient usage.
}

// WdkServiceRecordColumns defines and stores column names for table wdk_service_record.
type WdkServiceRecordColumns struct {
	Id           string // 服务记录ID
	ProjectId    string // 所属项目ID
	ServiceTime  string // 服务时间
	XchName      string // 行程涵文件名
	XchOriginUrl string // 原始行程涵url
	XchPdfUrl    string // pdf行程涵url
	Remark       string // 备注
	CreateAt     string // 创建时间
	UpdateAt     string // 更新时间
	DeletedAt    string // 软删除时间
}

//  wdkServiceRecordColumns holds the columns for table wdk_service_record.
var wdkServiceRecordColumns = WdkServiceRecordColumns{
	Id:           "id",
	ProjectId:    "project_id",
	ServiceTime:  "service_time",
	XchName:      "xch_name",
	XchOriginUrl: "xch_origin_url",
	XchPdfUrl:    "xch_pdf_url",
	Remark:       "remark",
	CreateAt:     "create_at",
	UpdateAt:     "update_at",
	DeletedAt:    "deleted_at",
}

// NewWdkServiceRecordDao creates and returns a new DAO object for table data access.
func NewWdkServiceRecordDao() *WdkServiceRecordDao {
	return &WdkServiceRecordDao{
		group:   "default",
		table:   "wdk_service_record",
		columns: wdkServiceRecordColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *WdkServiceRecordDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *WdkServiceRecordDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *WdkServiceRecordDao) Columns() WdkServiceRecordColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *WdkServiceRecordDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *WdkServiceRecordDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *WdkServiceRecordDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
