// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// WdkFileCommentDao is the data access object for table wdk_file_comment.
type WdkFileCommentDao struct {
	table   string                // table is the underlying table name of the DAO.
	group   string                // group is the database configuration group name of current DAO.
	columns WdkFileCommentColumns // columns contains all the column names of Table for convenient usage.
}

// WdkFileCommentColumns defines and stores column names for table wdk_file_comment.
type WdkFileCommentColumns struct {
	AuditUid  string // 审核员用户ID
	FileId    string // 审核的文件ID
	Page      string // 文件页码
	AuditName string // 审核人员姓名
	Comment   string // 每页评价内容
	CreateAt  string // 创建时间
	UpdateAt  string // 更新时间
	DeletedAt string // 软删除时间
}

//  wdkFileCommentColumns holds the columns for table wdk_file_comment.
var wdkFileCommentColumns = WdkFileCommentColumns{
	AuditUid:  "audit_uid",
	FileId:    "file_id",
	Page:      "page",
	AuditName: "audit_name",
	Comment:   "comment",
	CreateAt:  "create_at",
	UpdateAt:  "update_at",
	DeletedAt: "deleted_at",
}

// NewWdkFileCommentDao creates and returns a new DAO object for table data access.
func NewWdkFileCommentDao() *WdkFileCommentDao {
	return &WdkFileCommentDao{
		group:   "default",
		table:   "wdk_file_comment",
		columns: wdkFileCommentColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *WdkFileCommentDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *WdkFileCommentDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *WdkFileCommentDao) Columns() WdkFileCommentColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *WdkFileCommentDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *WdkFileCommentDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *WdkFileCommentDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
